@startuml
'https://plantuml.com/activity-diagram-beta

- KSMLTopologyTest
:KSMLTopologyTestContextProvider
    - provideTestTemplateInvocationContexts();
floating note right
returns 
""Stream<TestTemplateInvocationContext>""
end note    
:KSMLTopologyTestInvocationContext
    - getAdditionalExtensions();
floating note right
returns ""List<Extension>""
end note
- KSMLTopologyTestExtension


@enduml
